import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.scss'
import ProductContainerComponent from '@/components/productContainer'
import { itemStore } from "@/services/exampleDB";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.productContainer}>
          {itemStore.map((item, i) => {
            return (
            <ProductContainerComponent
              key={item.id}
              name={item.name}
              price={item.price}
              description={item.description}
              image={item.image}
            ></ProductContainerComponent>
            )
          })}
        </div>
      </main>
    </>
  )
}
