import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.scss'
import ProductContainerComponent from '@/components/productContainer'
import { itemStore } from "@/services/exampleDB";
import CartButtonComponent from '@/components/cartButton'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.headerContainer}>
          <Link style={{textDecoration: "none"}} href={"/"}>
            <div className={styles.title}><Image height={20} width={20} src={"/home.svg"} alt="home icon"></Image> Coffee Store</div>
          </Link>
          {/* <Image src={"/pageDivider.svg"} alt='graphic header image' height={20} width={100}></Image> */}
          <CartButtonComponent></CartButtonComponent>
        </div>
        <div className={styles.productContainer}>
          {itemStore.map((item, i) => {
            return (
            <ProductContainerComponent
              key={item.id + i}
              id={item.id}
              name={item.name}
              price={item.price}
              description={item.description}
              image={item.image}
              type={item.type}
            ></ProductContainerComponent>
            )
          })}
        </div>
      </main>
    </>
  )
}
