import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import ProductContainerComponent from '@/components/productContainer'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <ProductContainerComponent
          name='Americano Hot'
          price={3.25}
          description={"A delicious staple on our menu."}
          image={"/coffee.svg"}
        ></ProductContainerComponent>
      </main>
    </>
  )
}
